print("导入模块的方法：")
print("	1. import 模块名")
print("		使用方法：模块名.功能名(函数，类，变量......)")
print("	2. from 模块名 import 功能名")
print("		使用方法：功能名")
print("注意：")
print("	1. __all__变量的使用；")
print("		写法：__all__ = [\"函数名\",\"类名\",\"变量名\"....]")
print("		在模块中添加__all__变量后，在使用第二种方法导入模块时，只能导入变量中添加的功能；")
print("		使用第一种方法导入模块，不受__all__变量影响。")
print("	2. __name__变量的使用")
print("		因为导入模块时会执行模块中的代码，所以有可能收到模块中测试代码的影响。")
print("		可以通过__name__变量的妙用解决这个问题。")
print("		固定格式：")
print("		def main():")
print("			pass # 测试代码")
print("		# 作为模块被导入时，__name__为\"模块的名字\"，")
print("		# 作为文件被执行时，__name__为\"__main__\"，")
print("		if __name__ == \"__main__\":")
print("			main()")
